name: Build as local checkout

on:
  # push on master branch
  push:
    branches: [master]
  # triggered manually
  workflow_dispatch:
  # triggered by pull requests
  pull_request:

jobs:
  local-eisvogel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make eisvogel
      - uses: actions/upload-artifact@v4
        with:
          name: thesis_eisvogel_local
          path: thesis.pdf
          overwrite: true
  local-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make simple
      - uses: actions/upload-artifact@v4
        with:
          name: thesis_simple_local
          path: thesis.pdf
          overwrite: true
